  $(document).ready(function(){
  $('.modal').modal();
  });
  $(document).ready(function(){
  $('.collapsible').collapsible();
  });
  $(document).ready(function(){
    $('.tabs').tabs();
  });